version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_guesscarsyear
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guesscarsyear_db
      MYSQL_USER: vdionysio
      MYSQL_PASSWORD: pepelegal
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
